name: Windows 10

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999


    steps:
    - name: Download
      run: Invoke-WebRequest https://files.xtunnel.ru/xtunnel/1.0.14/xTunnel.win-x64.1.0.14.zip -OutFile xtunnel.zip
    - name: Extract
      run: Expand-Archive xtunnel.zip
    - name: Auth
      run: .\xtunnel\xtunnel.exe authtoken $Env:XTUNNEL_AUTH_TOKEN
      env:
        XTUNNEL_AUTH_TOKEN: ${{ secrets.XTUNNEL_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
    - name: Create Tunnel
      run: .\xtunnel\xtunnel.exe tcp 3389
