name: Windows Server

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2016
    timeout-minutes: 9999


    steps:
    - name: Download
      run: Invoke-WebRequest https://cloudpub.ru/download/stable/clo-1.4.86-stable-windows-x86_64.zip -OutFile clo.zip
    - name: Extract
      run: Expand-Archive clo.zip
    - name: Auth
      run: .\clo\clo.exe set token $Env:CLO_AUTH_TOKEN
      env:
        CLO_AUTH_TOKEN: ${{ secrets.CLO_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
    - name: Create Tunnel
      run: .\clo\clo.exe publish tcp 3389
